remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Gabriel Notte - 'Emergency Call' PORTFOLIO
description: Portfolio containiny my work on 'Emergency Call'
markdown: GFM

